name: faecauth
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+56

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  velocity_x: ^4.2.1
  permission_handler: ^11.3.1
  responsive_sizer: ^3.3.1
  lottie: ^3.1.3
  face_liveness: 
    path : local_packages/face_liveness/
  fluttertoast: ^8.2.6
  path_provider: ^2.1.3
  get: ^4.6.6
  shared_preferences: ^2.2.3
  loading_animation_widget: ^1.2.1
  get_storage: ^2.1.1
  http: ^1.2.1
  syncfusion_flutter_calendar: ^26.1.40+1
  animated_splash_screen: ^1.3.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  rename_app: ^1.6.1
  intl: ^0.19.0
  month_picker_dialog: ^4.0.1
  flutter_launcher_icons: ^0.13.1
  in_app_update: ^4.2.3
 

  
 
  # percent_indicator: ^4.2.3
  # floor: ^1.5.0
  # sqflite: ^2.3.3+1
  # floor_generator: ^1.5.0
  build_runner: ^2.4.11
  connectivity_plus: ^6.0.3
  # device_info_plus: ^10.1.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  table_calendar: ^3.1.2
  # flutter_heat_map: ^1.2.1
  quickalert: ^1.1.0
  dio: ^5.5.0+1
  google_maps_flutter: ^2.7.1
  text_marquee: ^0.0.2
  # flutter_upgrade_version: ^1.1.6
  file_picker: ^8.1.2
  flutter_pdfview: ^1.3.2
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/
    - assets/IntroScreenVideo.mp4

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/latest_logo.jpg"
  min_sdk_android: 21